### ISSUE TITLE
[Week1]

### ISSUE THREAD

**Issue by adaruru** [Lidemy/mentor-program-3rd-Ponchimeow#4]

**Comment by adaruru** [comment]
請問 "請將答案寫在 hw1.md。" 的意思是什麼?

HW1題目是:請用文字一步步敘述應該如何交作業。
是指 edit the file in your fork on this project 嗎?
還是 issue 的 branch 下新的 txt 檔?
或是別的意思?

謝謝

**Comment by cwenwen** [comment]
@adaruru 你 fork 到別的同學的 repo 了，就連這頁也是別的同學的XD
再去把老師 Lidemy 上的影片看熟一點吧～

**Comment by Ponchimeow** [comment]
老師會用你的帳號開一個帶有你帳號的作業專案，clone那份專案至你本機進行作業撰寫，作業期間的 git 操作在交作業流程影片裡老師有解說，有點像是每個同學跟老師有一個共用的筆記本，你寫完作業後再給老師看，只是每個同學封面的名字不同。

收到信我還想說怎了XD
